let amountsArray = [
  1, 1, 1, 4, 2, 4, 1, 1, 100, 100, 1, 3, 3, 500, 1, 100, "",
];
let unitArray = [
  "Stück(e)",
  "Stück(e)",
  "Stück(e)",
  "Stück(e)",
  "Stück(e)",
  "Stück(e)",
  "Handvoll",
  "Stück(e)",
  "ml",
  "ml",
  "EL",
  "Stück(e)",
  "Stück(e)",
  "g",
  "Stück(e)",
  "g",
  "",
];
let ingredientsArry = [
  "Suppenhuhn",
  "Lauchstange(n)",
  "Zwiebel(n)",
  "Knoblauchzehe(n)",
  "Ingwerwurzel",
  "Karotte(n)",
  "Algen, optional",
  "Schweinefilet(s)",
  "Sojasauce, japanisch",
  "Reiswein oder Sake",
  "Zucker",
  "Frühlingszwiebel(n)",
  "Ei(er)",
  "Ramen-Nudeln",
  "Noriblatt",
  "Sojasprossen",
  "Salz und Pfeffer",
];
